name: Go
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        go: [ '1.17', '1.18' ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Go ${{ matrix.go }} build / test
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          go install
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .
